name: margherita
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0' # CORRECTED: A valid range for the Dart "language rules".

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  geolocator: ^11.0.0
  just_audio: ^0.9.36
  http: ^1.2.1
  google_maps_flutter: ^2.6.1
  shared_preferences: ^2.5.3
  path_provider: ^2.0.11
  introduction_screen: ^3.1.12
  lottie: ^3.0.0 # For cool animations
  provider: ^6.0.5 

  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0 # CORRECTED: A valid version for the "code checking" tool.


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/sounds/
    - assets/audio/lang_en/antonio/
    - assets/audio/lang_en/caterina/
    - assets/audio/lang_en/d/
    - assets/audio/lang_en/donato/
    - assets/audio/lang_en/margherita/
    - assets/audio/lang_it/antonio/
    - assets/audio/lang_it/caterina/
    - assets/audio/lang_it/d/
    - assets/audio/lang_it/donato/
    - assets/audio/lang_it/margherita/
    - assets/tour.json